In [6]:
import sys
sys.path.append("../")

%load_ext autoreload
%autoreload 2

from src.data.load import load_ratings

ratings = load_ratings()
print("Shape:", ratings.shape)
print(ratings.dtypes)
ratings.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Shape: (1048575, 4)
userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [7]:
n_users = ratings["userId"].nunique()
n_movies = ratings["movieId"].nunique()
n_ratings = len(ratings)

possible_cells = n_users * n_movies
sparsity = 1 - (n_ratings / possible_cells)

print(f"Users: {n_users:,}")
print(f"Movies: {n_movies:,}")
print(f"Ratings: {n_ratings:,}")
print(f"Possible cells (dense matrix): {possible_cells:,}")
print(f"Sparsity: {sparsity:.4%}")

Users: 7,045
Movies: 22,240
Ratings: 1,048,575
Possible cells (dense matrix): 156,680,800
Sparsity: 99.3308%

In [8]:
user_ids = ratings["userId"].unique()
movie_ids = ratings["movieId"].unique()

user_id_to_index = {user_id: idx for idx, user_id in enumerate(user_ids)}
movie_id_to_index = {movie_id: idx for idx, movie_id in enumerate(movie_ids)}

index_to_user_id = {idx: user_id for user_id, idx in user_id_to_index.items()}
index_to_movie_id = {idx: movie_id for movie_id, idx in movie_id_to_index.items()}

print("Number of user indices:", len(user_id_to_index))
print("Number of movie indices:", len(movie_id_to_index))

Number of user indices: 7045
Number of movie indices: 22240

In [9]:
from scipy.sparse import csr_matrix
import numpy as np

row_indices = ratings["userId"].map(user_id_to_index).values
col_indices = ratings["movieId"].map(movie_id_to_index).values
rating_values = ratings["rating"].values

user_item_matrix = csr_matrix(
    (rating_values, (row_indices, col_indices)),
    shape=(n_users, n_movies)
)

print("Matrix shape:", user_item_matrix.shape)
print("Matrix dtype:", user_item_matrix.dtype)
print("Non-zero entries:", user_item_matrix.nnz)
print("Matches ratings count:", user_item_matrix.nnz == n_ratings)

Matrix shape: (7045, 22240)
Matrix dtype: float64
Non-zero entries: 1048575
Matches ratings count: True

In [10]:
import joblib
from scipy import sparse
from src.config import (
    USER_ITEM_MATRIX_PATH,
    USER_ID_TO_INDEX_PATH,
    MOVIE_ID_TO_INDEX_PATH,
    INDEX_TO_MOVIE_ID_PATH,
)

sparse.save_npz(USER_ITEM_MATRIX_PATH, user_item_matrix)
joblib.dump(user_id_to_index, USER_ID_TO_INDEX_PATH)
joblib.dump(movie_id_to_index, MOVIE_ID_TO_INDEX_PATH)
joblib.dump(index_to_movie_id, INDEX_TO_MOVIE_ID_PATH)

print("Saved matrix and mappings.")

Saved matrix and mappings.

In [11]:
from sklearn.decomposition import TruncatedSVD

N_COMPONENTS = 50  # number of latent factors — a starting point, we'll tune later

svd = TruncatedSVD(n_components=N_COMPONENTS, random_state=42)

user_factors = svd.fit_transform(user_item_matrix)   # shape: (n_users, N_COMPONENTS)
movie_factors = svd.components_.T                     # shape: (n_movies, N_COMPONENTS)

print("user_factors shape:", user_factors.shape)
print("movie_factors shape:", movie_factors.shape)
print("Explained variance ratio (sum):", svd.explained_variance_ratio_.sum())

user_factors shape: (7045, 50)
movie_factors shape: (22240, 50)
Explained variance ratio (sum): 0.3714462414254448

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

def most_similar_movies_collab(movie_id, n=10):
    if movie_id not in movie_id_to_index:
        return f"movieId {movie_id} not found in matrix."

    idx = movie_id_to_index[movie_id]
    target_vector = movie_factors[idx].reshape(1, -1)

    similarities = cosine_similarity(target_vector, movie_factors).flatten()
    similar_indices = similarities.argsort()[-(n+1):][::-1]
    similar_indices = [i for i in similar_indices if i != idx][:n]

    results = []
    for i in similar_indices:
        results.append({
            "movieId": index_to_movie_id[i],
            "similarity": similarities[i]
        })
    return results

# Toy Story's movieId in MovieLens is 1
most_similar_movies_collab(1, n=10)

[{'movieId': np.int64(3114), 'similarity': np.float64(0.655869482135861)},
 {'movieId': np.int64(979), 'similarity': np.float64(0.5907524632712242)},
 {'movieId': np.int64(1448), 'similarity': np.float64(0.5907524632712242)},
 {'movieId': np.int64(1510), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1524), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1462), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1424), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1470), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1443), 'similarity': np.float64(0.5907524632712241)},
 {'movieId': np.int64(1420), 'similarity': np.float64(0.5907524632712241)}]

In [13]:
from src.data.load import load_movies

movies_lookup = load_movies().set_index("movieId")["title"]

def most_similar_movies_collab_readable(movie_id, n=10):
    results = most_similar_movies_collab(movie_id, n=n)
    if isinstance(results, str):
        return results

    for r in results:
        r["title"] = movies_lookup.get(r["movieId"], "Unknown")

    return results

most_similar_movies_collab_readable(1, n=10)  # Toy Story

[{'movieId': np.int64(3114),
  'similarity': np.float64(0.655869482135861),
  'title': 'Toy Story 2 (1999)'},
 {'movieId': np.int64(979),
  'similarity': np.float64(0.5907524632712242),
  'title': 'Nothing Personal (1995)'},
 {'movieId': np.int64(1448),
  'similarity': np.float64(0.5907524632712242),
  'title': 'Fire on the Mountain (1996)'},
 {'movieId': np.int64(1510),
  'similarity': np.float64(0.5907524632712241),
  'title': "Brother's Kiss, A (1997)"},
 {'movieId': np.int64(1524),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Turning, The (1992)'},
 {'movieId': np.int64(1462),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Unforgotten: Twenty-Five Years After Willowbrook (1996)'},
 {'movieId': np.int64(1424),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Inside (1996)'},
 {'movieId': np.int64(1470),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Rhyme & Reason (1997)'},
 {'movieId': np.int64(1443),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Tickle in the Heart, A (1996)'},
 {'movieId': np.int64(1420),
  'similarity': np.float64(0.5907524632712241),
  'title': 'Message to Love: The Isle of Wight Festival (1996)'}]

In [14]:
from src.recommend import recommend

print("=== Content-based recommendations for Toy Story (1995) ===")
display(recommend("Toy Story (1995)", n=10))

print("\n=== Collaborative recommendations for Toy Story (movieId=1) ===")
for r in most_similar_movies_collab_readable(1, n=10):
    print(f"{r['title']}  (similarity={r['similarity']:.3f})")

=== Content-based recommendations for Toy Story (1995) ===

,movieId,title,genres,similarity_score
3021,3114,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,0.930007
2264,2355,"Bug's Life, A (1998)",Adventure|Animation|Children|Comedy,0.851211
4780,4886,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,0.786317
14813,78499,Toy Story 3 (2010),Adventure|Animation|Children|Comedy|Fantasy|IMAX,0.770890
59767,201588,Toy Story 4 (2019),Adventure|Animation|Children|Comedy,0.730895
39485,157296,Finding Dory (2016),Adventure|Animation|Comedy,0.718785
6258,6377,Finding Nemo (2003),Adventure|Animation|Children|Comedy,0.712220
8246,8961,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,0.706227
19870,103141,Monsters University (2013),Adventure|Animation|Comedy,0.699954
48035,175831,Lou (2017),Animation,0.673460

=== Collaborative recommendations for Toy Story (movieId=1) ===
Toy Story 2 (1999)  (similarity=0.656)
Nothing Personal (1995)  (similarity=0.591)
Fire on the Mountain (1996)  (similarity=0.591)
Brother's Kiss, A (1997)  (similarity=0.591)
Turning, The (1992)  (similarity=0.591)
Unforgotten: Twenty-Five Years After Willowbrook (1996)  (similarity=0.591)
Inside (1996)  (similarity=0.591)
Rhyme & Reason (1997)  (similarity=0.591)
Tickle in the Heart, A (1996)  (similarity=0.591)
Message to Love: The Isle of Wight Festival (1996)  (similarity=0.591)

In [15]:
import numpy as np

def recommend_for_user(user_id, n=10):
    if user_id not in user_id_to_index:
        return f"userId {user_id} not found."

    user_idx = user_id_to_index[user_id]
    user_vector = user_factors[user_idx]  # shape: (N_COMPONENTS,)

    # Predicted rating for every movie = dot product of user vector and each movie vector
    predicted_scores = movie_factors @ user_vector  # shape: (n_movies,)

    # Exclude movies this user already rated
    already_rated_movie_ids = set(
        ratings.loc[ratings["userId"] == user_id, "movieId"]
    )
    already_rated_indices = {
        movie_id_to_index[mid] for mid in already_rated_movie_ids
        if mid in movie_id_to_index
    }

    # Rank all movie indices by predicted score, skipping already-rated ones
    top_indices = predicted_scores.argsort()[::-1]
    top_indices = [i for i in top_indices if i not in already_rated_indices][:n]

    results = []
    for i in top_indices:
        movie_id = index_to_movie_id[i]
        results.append({
            "movieId": movie_id,
            "title": movies_lookup.get(movie_id, "Unknown"),
            "predicted_score": predicted_scores[i]
        })
    return results

# Try it on an arbitrary real user from your dataset
sample_user_id = ratings["userId"].iloc[0]
print("Recommending for userId:", sample_user_id)
recommend_for_user(sample_user_id, n=10)

Recommending for userId: 1

[{'movieId': np.int64(6874),
  'title': 'Kill Bill: Vol. 1 (2003)',
  'predicted_score': np.float64(1.3985061866490536)},
 {'movieId': np.int64(778),
  'title': 'Trainspotting (1996)',
  'predicted_score': np.float64(1.3212750636019315)},
 {'movieId': np.int64(7153),
  'title': 'Lord of the Rings: The Return of the King, The (2003)',
  'predicted_score': np.float64(1.2335396574659103)},
 {'movieId': np.int64(7438),
  'title': 'Kill Bill: Vol. 2 (2004)',
  'predicted_score': np.float64(1.2195768343833033)},
 {'movieId': np.int64(4993),
  'title': 'Lord of the Rings: The Fellowship of the Ring, The (2001)',
  'predicted_score': np.float64(1.156409652556753)},
 {'movieId': np.int64(4306),
  'title': 'Shrek (2001)',
  'predicted_score': np.float64(1.1462003329311803)},
 {'movieId': np.int64(4226),
  'title': 'Memento (2000)',
  'predicted_score': np.float64(1.1186446250600175)},
 {'movieId': np.int64(4878),
  'title': 'Donnie Darko (2001)',
  'predicted_score': np.float64(1.0314603118676684)},
 {'movieId': np.int64(4848),
  'title': 'Mulholland Drive (2001)',
  'predicted_score': np.float64(1.0071735561254134)},
 {'movieId': np.int64(4886),
  'title': 'Monsters, Inc. (2001)',
  'predicted_score': np.float64(0.9878123987261914)}]

In [16]:
import numpy as np
import joblib
from src.config import USER_FACTORS_PATH, MOVIE_FACTORS_PATH, SVD_MODEL_PATH

np.save(USER_FACTORS_PATH, user_factors)
np.save(MOVIE_FACTORS_PATH, movie_factors)
joblib.dump(svd, SVD_MODEL_PATH)

print("Saved user_factors, movie_factors, and the fitted SVD model.")

Saved user_factors, movie_factors, and the fitted SVD model.

In [17]:
user_rated_movies = (
    ratings.groupby("userId")["movieId"]
    .apply(set)
    .to_dict()
)

print("Number of users in lookup:", len(user_rated_movies))
print("Example — userId", sample_user_id, "has rated", len(user_rated_movies[sample_user_id]), "movies")

Number of users in lookup: 7045
Example — userId 1 has rated 70 movies

In [18]:
from src.config import USER_RATED_MOVIES_PATH

joblib.dump(user_rated_movies, USER_RATED_MOVIES_PATH)
print("Saved user_rated_movies lookup.")

Saved user_rated_movies lookup.

In [19]:
import sys
sys.path.append("../")

%load_ext autoreload
%autoreload 2

from src.recommend_user import recommend_for_user as recommend_user_standalone

recommend_user_standalone(sample_user_id, n=10)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

[{'movieId': np.int64(6874),
  'predicted_score': np.float64(1.3985061866490536),
  'title': 'Kill Bill: Vol. 1 (2003)'},
 {'movieId': np.int64(778),
  'predicted_score': np.float64(1.3212750636019315),
  'title': 'Trainspotting (1996)'},
 {'movieId': np.int64(7153),
  'predicted_score': np.float64(1.2335396574659103),
  'title': 'Lord of the Rings: The Return of the King, The (2003)'},
 {'movieId': np.int64(7438),
  'predicted_score': np.float64(1.2195768343833033),
  'title': 'Kill Bill: Vol. 2 (2004)'},
 {'movieId': np.int64(4993),
  'predicted_score': np.float64(1.156409652556753),
  'title': 'Lord of the Rings: The Fellowship of the Ring, The (2001)'},
 {'movieId': np.int64(4306),
  'predicted_score': np.float64(1.1462003329311803),
  'title': 'Shrek (2001)'},
 {'movieId': np.int64(4226),
  'predicted_score': np.float64(1.1186446250600175),
  'title': 'Memento (2000)'},
 {'movieId': np.int64(4878),
  'predicted_score': np.float64(1.0314603118676684),
  'title': 'Donnie Darko (2001)'},
 {'movieId': np.int64(4848),
  'predicted_score': np.float64(1.0071735561254134),
  'title': 'Mulholland Drive (2001)'},
 {'movieId': np.int64(4886),
  'predicted_score': np.float64(0.9878123987261914),
  'title': 'Monsters, Inc. (2001)'}]

In [20]:
import numpy as np

np.random.seed(42)

def train_test_split_per_user(ratings, test_size=0.2):
    """
    For each user, randomly hold out `test_size` fraction of their ratings
    as test data, keep the rest as train data. This avoids leaking a user's
    full rating history into training while still guaranteeing every test
    user has some training history for the model to learn from.
    """
    test_mask = np.zeros(len(ratings), dtype=bool)

    for user_id, group in ratings.groupby("userId"):
        n_test = max(1, int(len(group) * test_size))
        test_indices = np.random.choice(group.index, size=n_test, replace=False)
        test_mask[ratings.index.get_indexer(test_indices)] = True

    train_ratings = ratings[~test_mask].reset_index(drop=True)
    test_ratings = ratings[test_mask].reset_index(drop=True)
    return train_ratings, test_ratings

train_ratings, test_ratings = train_test_split_per_user(ratings, test_size=0.2)

print("Train ratings:", len(train_ratings))
print("Test ratings:", len(test_ratings))
print("Users in train:", train_ratings["userId"].nunique())
print("Users in test:", test_ratings["userId"].nunique())

Train ratings: 841560
Test ratings: 207015
Users in train: 7045
Users in test: 7045

In [21]:
from scipy.sparse import csr_matrix

# Create ID mappings using TRAIN data only
train_user_ids = train_ratings["userId"].unique()
train_movie_ids = train_ratings["movieId"].unique()

train_user_id_to_index = {
    user_id: idx
    for idx, user_id in enumerate(train_user_ids)
}

train_movie_id_to_index = {
    movie_id: idx
    for idx, movie_id in enumerate(train_movie_ids)
}

print("Training users:", len(train_user_id_to_index))
print("Training movies:", len(train_movie_id_to_index))

Training users: 7045
Training movies: 20687

In [22]:
# Convert training ratings into a sparse user-item matrix

row_indices = train_ratings["userId"].map(
    train_user_id_to_index
).values

col_indices = train_ratings["movieId"].map(
    train_movie_id_to_index
).values

rating_values = train_ratings["rating"].values

train_user_item_matrix = csr_matrix(
    (
        rating_values,
        (row_indices, col_indices)
    ),
    shape=(
        len(train_user_id_to_index),
        len(train_movie_id_to_index)
    )
)

print(
    "Training matrix shape:",
    train_user_item_matrix.shape
)

print(
    "Non-zero ratings:",
    train_user_item_matrix.nnz
)

Training matrix shape: (7045, 20687)
Non-zero ratings: 841560

In [23]:
from sklearn.decomposition import TruncatedSVD

# Train SVD using TRAIN data only
svd_train = TruncatedSVD(
    n_components=50,
    random_state=42
)

user_latent_train = svd_train.fit_transform(
    train_user_item_matrix
)

print("User latent matrix shape:", user_latent_train.shape)
print("Movie latent matrix shape:", svd_train.components_.shape)

print(
    "Explained variance:",
    svd_train.explained_variance_ratio_.sum()
)

User latent matrix shape: (7045, 50)
Movie latent matrix shape: (50, 20687)
Explained variance: 0.3102197630612335

In [24]:
# Reconstruct predicted user-movie scores

predicted_ratings = (
    user_latent_train @ svd_train.components_
)

print(
    "Predicted ratings matrix shape:",
    predicted_ratings.shape
)

Predicted ratings matrix shape: (7045, 20687)

In [25]:
# Create reverse mappings

index_to_train_user_id = {
    idx: user_id
    for user_id, idx in train_user_id_to_index.items()
}

index_to_train_movie_id = {
    idx: movie_id
    for movie_id, idx in train_movie_id_to_index.items()
}

print(
    "User mapping ready:",
    len(index_to_train_user_id)
)

print(
    "Movie mapping ready:",
    len(index_to_train_movie_id)
)

User mapping ready: 7045
Movie mapping ready: 20687

In [26]:
def recommend_for_user(
    user_id,
    n=10
):
    """
    Generate collaborative-filtering recommendations
    for a user using the SVD model trained on train data.
    """

    # Check whether user exists in training data
    if user_id not in train_user_id_to_index:
        return f"User {user_id} not found in training data."

    user_idx = train_user_id_to_index[user_id]

    # Get predicted scores for this user
    user_scores = predicted_ratings[user_idx].copy()

    # Movies already rated by this user in TRAIN data
    seen_movie_ids = set(
        train_ratings[
            train_ratings["userId"] == user_id
        ]["movieId"]
    )

    # Remove already-seen movies
    for movie_id in seen_movie_ids:

        if movie_id in train_movie_id_to_index:
            movie_idx = train_movie_id_to_index[movie_id]
            user_scores[movie_idx] = -np.inf

    # Get top-N movies
    top_indices = np.argsort(
        user_scores
    )[-n:][::-1]

    # Convert matrix indices back to movie IDs
    recommended_movie_ids = [
        index_to_train_movie_id[idx]
        for idx in top_indices
    ]

    return recommended_movie_ids

In [27]:
# Test recommendations for one user

test_user_id = train_user_ids[0]

recommendations = recommend_for_user(
    test_user_id,
    n=10
)

print("User:", test_user_id)
print("Recommended movie IDs:")
print(recommendations)

User: 1
Recommended movie IDs:
[np.int64(4226), np.int64(2571), np.int64(7153), np.int64(2959), np.int64(4878), np.int64(4306), np.int64(5995), np.int64(8961), np.int64(4993), np.int64(4848)]

In [29]:
import pandas as pd
import numpy as np

In [30]:
# Load movie information

movies = pd.read_csv(
    "../data/raw/movies.csv"
)

# Display recommended movies with titles and genres

recommendation_df = movies[
    movies["movieId"].isin(recommendations)
].copy()

# Preserve recommendation ranking
recommendation_df["rank"] = recommendation_df[
    "movieId"
].apply(
    lambda movie_id: recommendations.index(movie_id) + 1
)

recommendation_df = recommendation_df.sort_values(
    "rank"
)

recommendation_df

,movieId,title,genres,rank
4122,4226,Memento (2000),Mystery|Thriller,1
2480,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,2
7028,7153,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,3
2867,2959,Fight Club (1999),Action|Crime|Drama|Thriller,4
4772,4878,Donnie Darko (2001),Drama|Mystery|Sci-Fi|Thriller,5
4201,4306,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,6
5883,5995,"Pianist, The (2002)",Drama|War,7
8246,8961,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,8
4887,4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,9
4742,4848,Mulholland Drive (2001),Crime|Drama|Film-Noir|Mystery|Thriller,10

In [31]:
# Create a readable recommendation table

recommendation_rows = []

user_idx = train_user_id_to_index[test_user_id]

for rank, movie_id in enumerate(
    recommendations,
    start=1
):
    movie_idx = train_movie_id_to_index[movie_id]

    movie_info = movies[
        movies["movieId"] == movie_id
    ]

    if len(movie_info) == 0:
        continue

    recommendation_rows.append({
        "rank": rank,
        "movieId": movie_id,
        "title": movie_info.iloc[0]["title"],
        "genres": movie_info.iloc[0]["genres"],
        "svd_score": predicted_ratings[
            user_idx,
            movie_idx
        ]
    })

recommendation_df = pd.DataFrame(
    recommendation_rows
)

recommendation_df

,rank,movieId,title,genres,svd_score
0,1,4226,Memento (2000),Mystery|Thriller,1.474797
1,2,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1.144836
2,3,7153,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,1.104787
3,4,2959,Fight Club (1999),Action|Crime|Drama|Thriller,1.003461
4,5,4878,Donnie Darko (2001),Drama|Mystery|Sci-Fi|Thriller,0.951123
5,6,4306,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,0.929623
6,7,5995,"Pianist, The (2002)",Drama|War,0.912308
7,8,8961,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,0.907943
8,9,4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,0.906617
9,10,4848,Mulholland Drive (2001),Crime|Drama|Film-Noir|Mystery|Thriller,0.901597

In [32]:
# Prepare test ratings for evaluation

test_ratings_eval = test_ratings.copy()

# Only keep test movies that exist in the training movie mapping
test_ratings_eval = test_ratings_eval[
    test_ratings_eval["movieId"].isin(
        train_movie_id_to_index
    )
].copy()

print("Original test ratings:", len(test_ratings))
print(
    "Test ratings with known training movies:",
    len(test_ratings_eval)
)

print(
    "Coverage:",
    len(test_ratings_eval) / len(test_ratings)
)

Original test ratings: 207015
Test ratings with known training movies: 205338
Coverage: 0.9918991377436418

In [33]:
RELEVANCE_THRESHOLD = 4.0

test_relevant_eval = test_ratings_eval[
    test_ratings_eval["rating"] >= RELEVANCE_THRESHOLD
].copy()

print(
    "Relevant test ratings:",
    len(test_relevant_eval)
)

print(
    "Relevant test users:",
    test_relevant_eval["userId"].nunique()
)

Relevant test ratings: 102531
Relevant test users: 6912

In [34]:
# Prepare test ratings for collaborative evaluation

test_ratings_eval = test_ratings.copy()

# Keep only movies that were present during SVD training
test_ratings_eval = test_ratings_eval[
    test_ratings_eval["movieId"].isin(
        train_movie_id_to_index
    )
].copy()

print("Original test ratings:", len(test_ratings))

print(
    "Test ratings with known training movies:",
    len(test_ratings_eval)
)

print(
    "Movie coverage:",
    f"{len(test_ratings_eval) / len(test_ratings):.2%}"
)

Original test ratings: 207015
Test ratings with known training movies: 205338
Movie coverage: 99.19%

In [35]:
# Define relevant test interactions

RELEVANCE_THRESHOLD = 4.0

test_relevant_eval = test_ratings_eval[
    test_ratings_eval["rating"] >= RELEVANCE_THRESHOLD
].copy()

print(
    "Relevant test ratings:",
    len(test_relevant_eval)
)

print(
    "Users with relevant test ratings:",
    test_relevant_eval["userId"].nunique()
)

Relevant test ratings: 102531
Users with relevant test ratings: 6912

In [36]:
def generate_svd_recommendations(
    user_id,
    n=10
):
    """
    Generate top-N collaborative recommendations
    using the SVD model trained on training data.
    """

    if user_id not in train_user_id_to_index:
        return []

    user_idx = train_user_id_to_index[user_id]

    # Predicted scores for every training movie
    user_scores = predicted_ratings[user_idx].copy()

    # Remove movies already seen in training data
    seen_movie_ids = set(
        train_ratings[
            train_ratings["userId"] == user_id
        ]["movieId"]
    )

    for movie_id in seen_movie_ids:

        if movie_id in train_movie_id_to_index:
            movie_idx = train_movie_id_to_index[movie_id]
            user_scores[movie_idx] = -np.inf

    # Get top-N
    top_indices = np.argsort(
        user_scores
    )[-n:][::-1]

    return [
        index_to_train_movie_id[idx]
        for idx in top_indices
    ]

In [37]:
# Users who have relevant held-out test movies

evaluation_users_svd = (
    test_relevant_eval["userId"]
    .drop_duplicates()
)

print(
    "Users available for SVD evaluation:",
    len(evaluation_users_svd)
)

Users available for SVD evaluation: 6912

In [38]:
# Ground-truth relevant movies for each user

test_relevant_by_user_svd = (
    test_relevant_eval
    .groupby("userId")["movieId"]
    .apply(set)
    .to_dict()
)

print(
    "Ground-truth users:",
    len(test_relevant_by_user_svd)
)

Ground-truth users: 6912

In [40]:
import numpy as np


def precision_at_k(recommended_items, relevant_items, k):
    recommended_top_k = recommended_items[:k]

    relevant_count = sum(
        item in relevant_items
        for item in recommended_top_k
    )

    return relevant_count / k


def recall_at_k(recommended_items, relevant_items, k):
    if len(relevant_items) == 0:
        return 0.0

    recommended_top_k = recommended_items[:k]

    relevant_count = sum(
        item in relevant_items
        for item in recommended_top_k
    )

    return relevant_count / len(relevant_items)


def ndcg_at_k(recommended_items, relevant_items, k):
    recommended_top_k = recommended_items[:k]

    dcg = 0.0

    for position, item in enumerate(
        recommended_top_k,
        start=1
    ):
        if item in relevant_items:
            dcg += 1 / np.log2(position + 1)

    ideal_relevant = min(
        len(relevant_items),
        k
    )

    idcg = sum(
        1 / np.log2(position + 1)
        for position in range(
            1,
            ideal_relevant + 1
        )
    )

    if idcg == 0:
        return 0.0

    return dcg / idcg

In [41]:
K = 10

svd_evaluation_results = []

for i, user_id in enumerate(
    evaluation_users_svd,
    start=1
):

    recommendations = generate_svd_recommendations(
        user_id,
        n=K
    )

    relevant_movies = test_relevant_by_user_svd.get(
        user_id,
        set()
    )

    if len(recommendations) == 0 or len(relevant_movies) == 0:
        continue

    precision = precision_at_k(
        recommendations,
        relevant_movies,
        K
    )

    recall = recall_at_k(
        recommendations,
        relevant_movies,
        K
    )

    ndcg = ndcg_at_k(
        recommendations,
        relevant_movies,
        K
    )

    svd_evaluation_results.append({
        "userId": user_id,
        "precision@10": precision,
        "recall@10": recall,
        "ndcg@10": ndcg
    })

    if i % 500 == 0:
        print(
            f"Processed {i}/{len(evaluation_users_svd)} users"
        )

Processed 500/6912 users
Processed 1000/6912 users
Processed 1500/6912 users
Processed 2000/6912 users
Processed 2500/6912 users
Processed 3000/6912 users
Processed 3500/6912 users
Processed 4000/6912 users
Processed 4500/6912 users
Processed 5000/6912 users
Processed 5500/6912 users
Processed 6000/6912 users
Processed 6500/6912 users

In [42]:
K = 10

svd_evaluation_results = []

for i, user_id in enumerate(
    evaluation_users_svd,
    start=1
):

    recommendations = generate_svd_recommendations(
        user_id,
        n=K
    )

    relevant_movies = test_relevant_by_user_svd.get(
        user_id,
        set()
    )

    if len(recommendations) == 0 or len(relevant_movies) == 0:
        continue

    precision = precision_at_k(
        recommendations,
        relevant_movies,
        K
    )

    recall = recall_at_k(
        recommendations,
        relevant_movies,
        K
    )

    ndcg = ndcg_at_k(
        recommendations,
        relevant_movies,
        K
    )

    svd_evaluation_results.append({
        "userId": user_id,
        "precision@10": precision,
        "recall@10": recall,
        "ndcg@10": ndcg
    })

    if i % 500 == 0:
        print(
            f"Processed {i}/{len(evaluation_users_svd)} users"
        )

Processed 500/6912 users
Processed 1000/6912 users
Processed 1500/6912 users
Processed 2000/6912 users
Processed 2500/6912 users
Processed 3000/6912 users
Processed 3500/6912 users
Processed 4000/6912 users
Processed 4500/6912 users
Processed 5000/6912 users
Processed 5500/6912 users
Processed 6000/6912 users
Processed 6500/6912 users

In [43]:
svd_evaluation_df = pd.DataFrame(
    svd_evaluation_results
)

print(
    "Successfully evaluated users:",
    len(svd_evaluation_df)
)

svd_evaluation_df.head()

Successfully evaluated users: 6912

   userId  precision@10  recall@10   ndcg@10
0       1           0.0   0.000000  0.000000
1       2           0.6   0.250000  0.686715
2       3           0.7   0.097222  0.790951
3       4           0.2   0.100000  0.233651
4       5           0.4   0.307692  0.491180

In [44]:
mean_svd_precision = svd_evaluation_df["precision@10"].mean()
mean_svd_recall = svd_evaluation_df["recall@10"].mean()
mean_svd_ndcg = svd_evaluation_df["ndcg@10"].mean()

print(f"SVD Mean Precision@10: {mean_svd_precision:.4f}")
print(f"SVD Mean Recall@10:    {mean_svd_recall:.4f}")
print(f"SVD Mean NDCG@10:      {mean_svd_ndcg:.4f}")

SVD Mean Precision@10: 0.2290
SVD Mean Recall@10:    0.2244
SVD Mean NDCG@10:      0.3143